name: Check PR title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  Check-PR-title:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - name: Conventional PR Title
        uses: aslafy-z/conventional-pr-title-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
